version: '3.8'

services:


  process-exporter:
    image: ncabatoff/process-exporter
    container_name: process-exporter
    command: -procnames execution_bot
    pid: "host" # Permet au conteneur de voir les processus de la machine hôte
    ports: [ "9256:9256" ]


  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command: ['--config.file=/etc/prometheus/prometheus.yml']
    ports: ["9090:9090"]
    restart: unless-stopped

  loki:
    image: grafana/loki:latest
    container_name: loki
    volumes:
      - loki_data:/loki
    ports: ["3100:3100"]
    command: -config.file=/etc/loki/local-config.yaml
    restart: unless-stopped

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - ../logs:/var/log/mev-bot:ro # 'ro' = read-only (lecture seule)
      - ./promtail:/etc/promtail
    command: -config.file=/etc/promtail/promtail-config.yml
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana-provisioning:/etc/grafana/provisioning
    ports: ["3000:3000"]
    restart: unless-stopped

volumes:
  prometheus_data: {}
  loki_data: {}
  grafana_data: {}
